name: QA
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: sudo apt install clang-format
      - uses: actions/checkout@v3
      - name: clang-format
        run: clang-format -Werror --dry-run --style=file *.c
  build:
    runs-on: ubuntu-latest
    container:
      image: crazybolillo/microchip:xc8
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: docker-entrypoint.sh
      - name: Compile
        run: build-check.sh
